-- Wk06- FINAL ENHANCEMENT TABLE
-- FEATURES: 
-- An Inventory Review table.
-- This gives the App. an Additional ability to leave a comment or review 
-- on the vehicle detail page for logged in clients. A client should be able 
-- to see their own reviews and edit or delete them.
-- TASK-1:
-- I'm creating this table is to store these reviews.It will links the User (who wrote it) 
-- to the Vehicle (what they are writing about).
--
CREATE TABLE IF NOT EXISTS public.review (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_date timestamp with time zone NOT NULL DEFAULT now(),
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);